### ISSUE TITLE
hello about 8266 firebase

### ISSUE THREAD

**Issue by mesut25** [danygeevarghesesam/python-firebase-esp8266#3]
I am new to this topic. A simple video example for m

**Comment by danygeevarghesesam** [comment]
Esp 8266 is just a microcontroller that can run with micropython or arduino. This python script connects the microcontroller to the Internet and read data from a specific json file

**Comment by danygeevarghesesam** [comment]
> Esp 8266 is just a microcontroller that can run with micropython or arduino. This python script connects the microcontroller to the Internet and read data from a specific json file

The video is on the way...
